# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0011_auto_20171220_1324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnitures', models.CharField(max_length=120)),
                ('contents', models.TextField(help_text='seperate each item by comma')),
                ('excludes', models.TextField(blank=True, help_text='seperate each item by comma', null=True)),
                ('public', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('propertyitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', 'timestamp'],
            },
        ),
    ]
