# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='contents',
            new_name='itemdesc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='excludes',
            new_name='itemnote',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='furnitures',
            new_name='itemtype',
        ),
    ]
