# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
