# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20171219_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
