# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
