# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20171219_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
